name: Swift CI

# Trigger this action on push to the main branch
on:
  push:
    branches:
      - main  # You can adjust this to match the branch you want

jobs:
  build:
    runs-on: macos-latest  # Use the latest macOS runner, or specify a version (macOS-latest uses the latest available version of Xcode)

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'  # You can adjust the Ruby version if necessary

    - name: Install Fastlane
      run: gem install fastlane --no-ri --no-rdoc --no-document

    - name: Set up Xcode 10.1
      run: sudo xcode-select -s /Applications/Xcode_10.1.app

    - name: Install Dependencies (if needed)
      run: |
        bundle install  # If you have a Gemfile, use bundler to install dependencies

    - name: Run Tests with Fastlane
      run: fastlane scan --scheme TAU --device "iPhone XR"

